### ISSUE TITLE
Make all reserved Elixir words other variable names

### ISSUE THREAD

**Issue by wende** [wende/elmchemy#67]
Add:

## Example:
```elm
a fn = fn
```

**Comment by MorganPersson** [comment]
`fn` seems like a very reasonable ~~variable~~ value name in Elm(chemy). Why not spit out `_fn` in elixir for value `fn`?

**Comment by Baransu** [comment]
I think it's not a way to go. We should prepend all reserved names with `_` like @MorganPersson said and allow users to write as much Elm as possible. Making specific words forbidden will drive us away from Elm even more.

**Comment by wende** [comment]
Well, not exactly `_` since prepending with it in Elixir makes your variable(value) unusable. But I definitely agree with increasing flexibility of the system.

Updating the description

**Comment by wende** [comment]
We could append with _ but it's a common Elm design, and we definitely don't want any conflicts like

```
fn a = 1
fn_ b =2
```
compiling to
```
def fn_(a), do: 1
def fn_(b), do: 2
```

We need to come up with something both readable and as unique as possible

**Comment by OvermindDL1** [comment]
You can always stuff a `$` on the front of the variable name or so.  The Elixir AST supports bindings of any name/atom, the Elixir source syntax does not support it, that way you have both safety from reserved words and you know it will not interact with an elixir specific name as well.

**Comment by wende** [comment]
@OvermindDL1 But we don't really generate AST of Elixir, we generate the code (because indentation and readability)
So I don't see how we can really make a use of that :/

**Comment by OvermindDL1** [comment]
You probably should generate AST instead of source, it is far more reliable and safe against changes (it is actually pretty well designed except for a few odd precedence issues that the language itself shares).  Plus you can always pretty-print the AST to a unified elixir language display in the elixir syntax (just not always reversable).  :-)

**Comment by wende** [comment]
@OvermindDL1 
We put readability as a first class citizen, and it's really hard to ensure that if we can't enforce indentation ourselves. Plus there is a lot of tricks that would be incredibly time-taking to express in ast. For example expressions like that
```elm
 list |> reduce (+)  
``` 
compiling to
 ```
 list |> (reduce.((&+/0).()).())
```
Obviously it's hard to argue about any readability here, but I cannot emphasize how much I wouldn't want to try to express that manually in an AST.

**Comment by OvermindDL1** [comment]
> For example expressions like that

Actually I do rewrites like that in my mlelixir with relative ease.  :-)
https://github.com/OvermindDL1/typed_elixir/blob/79a520b0a03cee6f9dae0878608463638e05a7a9/lib/ml_elixir.ex#L1201-L1267
(Ignore the mess of code, that is entirely a play-project, not made for readability... also I rewrite to `fn->end` sets instead of `&`'s as elixir rewrites `&`'s into `fn->end` sets anyway, and it reduces my code since I can have generic bodies then, plus `&` usage I find highly unreadable...)  ^.^
